name: Build-Pack-Release
on:
  push:
    branches:
      - master
jobs:
  build_pack_release:
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FA_NPM_TOKEN: ${{secrets.FA_NPM_TOKEN}}
      SPACE_SERVICES_URL: ${{secrets.SPACE_SERVICES_URL}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, 'windows-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn install --network-timeout 1000000
      - name: Get daemon
        run: yarn download-daemon
      - name: Linux app pack and release
        if: matrix.os == 'ubuntu-latest'
        run: yarn electron-pack --linux
      - name: MacOS app pack and release
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        if: matrix.os == 'macos-latest'
        run: yarn electron-pack --mac
      - name: Windows app pack and release
        # env:
        #  CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
        #  CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
        if: matrix.os == 'windows-latest'
        run: yarn electron-pack --win --x64 --ia32
